@startuml

title Robot Worlds design
footer Class diagram

skinparam backgroundColor transparent

package nl.dirkgroot.robotworlds {
    package server {
        class SocketListener
        class MessageReceiver
        class World

        class Request
        class CommandResult
    }

    package client {
        class SocketClient
    }
}

SocketListener ..> MessageReceiver
MessageReceiver ..> World
MessageReceiver ..> Request
MessageReceiver ..> CommandResult

@enduml
