title: Dirk's blog
author: Dirk Groot
description: I love software development, maybe I should write about it...

social:
  github: dirkgroot

theme: minima

show_excerpts: true
github_username: dirkgroot

plugins:
  - jekyll-feed

exclude:
  - .idea/
